services: 
  api_test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_test
    restart: always
    volumes:
      - ./app:/var/www/html
      - ./docker_conf/apache/php.ini:/usr/local/etc/php/conf.d/app.ini
      - ./docker_conf/apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverseproxy"
      - "traefik.http.routers.loocation.rule=Host(`${URL}`)"
      # - "traefik.http.routers.loocation.entrypoints=websecure"
      # - "traefik.http.routers.loocation.tls=true"
      - traefik.http.services.api_test.loadbalancer.server.port=80
      - traefik.http.middlewares.mywwwredirect.redirectregex.regex=^https://www\.(.*)

    networks:
      - reverseproxy
  
networks:
  reverseproxy:
    name: reverseproxy
    external: true
